name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"]   # must match CI name exactly
    types:
      - completed

jobs:
  deploy:
    # run only when CI succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/myapp
            TAG=${{ github.event.workflow_run.head_sha }}

            # Install Docker (if not installed)
            sudo apt-get update -y
            sudo apt-get install -y docker.io

            # Stop and remove old container
            sudo docker rm -f myapp || true

            # Pull latest image with SHA tag
            sudo docker pull $IMAGE:$TAG

            # Run new container
            sudo docker run -d --name myapp -p 8080:80 $IMAGE:$TAG
